[options="header"]
[cols="1, 3, 3"]
|===
|Version | Bearbeitungsdatum   | Autor 
|...	| ... | ...
|===

= Entwicklerdokumentation

== Einführung und Ziele

=== Aufgabenstellung
Es soll eine Software für den Einsatz in einem Fitnessstudio entwickelt werden. Dabei sollen verschiedene
Geschäftsfelder berücksichtigt werden. In der Mitarbeiterverwaltung können die Mitarbeiter(_Staff_) des Fitnessstudios eingestellt,
bearbeitet und entlassen werden. Die Mitarbeiter haben verschiedene Aufgaben (Thekenkraft/Trainer) und Löhne.

Zum Monatsende wird für jeden Mitarbeiter ein Lohnschein (_Payslip_) als PDF erstellt. Die Mitarbeiter sollen einen eigenen Login (_Login_) bekommen,
um den Dienstplan (_Roster_) zu betrachten und den Lohnschein abzurufen. Der Dienstplan muss ebenfalls von Mitarbeitern erstellt
und bearbeitet werden können.

Es sollen ebenfalls alle Mitglieder (_Customer_) verwaltet werden können. Diese können in das Studio aufgenommen, bearbeitet und entlassen werden.
Um als Mitglied aufgenommen zu werden muss ein Vertrag abgeschlossen werden. +
Bei der Aufnahme (_Registrierung_) soll ein Log-in erstellt werden, mit dem der Kunde von zu Hause aus persönliche Daten, Vertrag und Probetraining verwalten kann.
Die monatlichen Gebühren werden per SEPA-Lastschrift vom Kunden abgebucht.

Jedes Mitglied erhält einen Code (_ReferralCode_), mit dem es beliebig viele neue Mitglieder anwerben kann.
Wird dieser Code bei der Registrierung eines anderen Mitgliedes angegeben, so wird ein bestimmter Betrag auf das Kundenkonto des Codeinhabers gutgeschrieben.
Jeder Kunde kann während seiner Mitgliedschaft mit einem Trainer ein Probetraining vereinbaren,
entweder direkt im Studio oder über das Internetportal des Studios. Eine Mitgliedschaft kann pro Jahr für einen Monat
ohne Gründe ausgesetzt und später nachgeholt werden.

Des Weiteren gibt es einen Eingangs- und Verkaufsbereich (_Bar_), dort meldet sich jedes Mitglied mit seiner Kunden-ID
bei Betreten des Studios an und bei Verlassen ab. An der Theke können auch Getränke, Nahrungsergänzungsmittel
oder Zubehör (_Article_) erworben werden, diese werden bar bezahlt oder direkt vom Guthabenkonto abgebucht.
Mitglied können dann monatlich sich ihre Rechnung (_Invoice_) online als PDF ausgeben lassen.

Die Artikel des Verkaufsbereiches lassen sich ebenfalls verwalten. Es müssen Artikel hinzugefügt, bearbeitet
und gelöscht werden können. Unterschreiten Artikel die Mindestmenge, dann werden sie einer Bestellliste hinzugefügt
und für die Mitarbeiter sichtbar gemacht. +
Artikel, die für den Verzehr gedacht sind, haben ein Verfallsdatum (_expirationDate_),
welches bei jedem Programmstart überprüft wird. Für erschiedene Artikel soll man für einen bestimmten Zeitraum
einen Rabatt (_Discount_) angeben können.

Online und nur für den Chef (_Boss_) sind Statistiken (_Statistic_) über laufende Kosten, Einnahmen, Kundenverhalten und Verkaufsartikel grafisch dargestellt.
Sowie verschiedene Einstellungen wie Vertragslaufzeit, monatliche Gebühren, Einladungsprämie, Öffnungszeiten usw. verwaltbar.

=== Qualitätsziele

==== Qualitätsanforderungen
Die folgende Tabelle zeigt, welche Qualitätsanforderungen in welchem Umfang erfüllt werden müssen.
Die erste Spalte listet die Qualitätsanforderungen auf, während in den folgenden Spalten ein "x" verwendet wird, um die Priorität zu kennzeichnen.
Die zugewiesene Priorität muss bei der Formulierung der konkreten nichtfunktionalen Anforderungen berücksichtigt werden.

1 = Nicht wichtig ..
5 = Sehr wichtig
[options="header", cols="3h, ^1, ^1, ^1, ^1, ^1"]
|===
|Qualitätsanforderungen| 1 | 2 | 3 | 4 | 5
|Wartbarkeit           |   |   |   | x |
|Benutzbarkeit         |   |   | x |   |
|Effizienz             |   |   |   | x |
|Funktionalität        |   |   |   |   | x
|Übertragbarkeit       | x |   |   |   | 
|Zuverlässigkeit       |   |   | x |   |
|Sicherheit            |   |   | x |   |
|Nutzerfreundlichkeit  |   | x |   |   |
|Erreichbarkeit        |   | x |   |   |
|===

==== Konkrete Nicht-Funktionale Anforderungen

[options="header"]
[cols="1h, 4"]
|===
|Ziel |Beschreibung 
|Zuverlässigkeit|Um die Zuverlässigkeit des Systems zu gewährleisten schreiben wir Anwendungs- und Akzeptanztests. So können Fehler leichter erkannt und die Zuverlässigkeit gewährleistet werden.
|Betriebszeit|Das System soll nur zu kurzen Wartungszeiten offline genommen werden. Sonst soll das System immer erreichbar sein. 
|Sicherheit| Die Daten der Nutzer sollen sicher verschlüsselt gespeichert werden.
|Effizienz|Der Code soll effizient sein. Redundanzen sollen vermieden werden, dass eine hohe Geschwindigkeit möglich ist.
|Funktionalität|Das System soll niemals abstürzen und alle Funktionen soll richtig funktionieren.
|===


== Randbedingungen

=== Hardware - Vorgaben

Eine Liste an benötigter Hardware, welche man zur Bedienung des Systems benötigt.

* Server
* Computer
* Tastatur
* Maus
* Monitor
* Internetanschluss

=== Software - Vorgaben 

Eine Liste der Software, welche benötigt wird um die Anwendung zu benutzen.

Die folgende (oder neuere) Java Version wird benötgit:

* Java 11

Die folgende (oder neuere) Suchmaschinen-Version wird benötigt:

* Internet Explorer/ Edge 10.0
* Firefox 4.0
* Google Chrome 4.0
* Opera 9.6


=== Produktnutzung
Die Software (_System_) soll auf einem Server laufen und dabei durchgängig über das Internet mit einem Browser
(z. B. Google Chrome, Firefox oder Safari) erreichbar sein. Hauptnutzungsgebiete sind dabei die Mitarbeiterverwaltung,
die Verkaufsstelle (_Bar_) und die Mitgliederverwaltung. Alle Felder sind über die gleiche Applikation mit verschiedenen
Log-ins (_Login_) erreichbar.

Alle sich anhäufende Daten sollen dabei dauerhaft in Form einer Datenbank gespeichert werden. +
Vertrauliche Daten, wie z. B. Passwörter, sollen verschlüsselt gesichert werden. Für den Umgang mit der Datenbank wird kein technisches
Verständnis verausgesetzt, denn deren Verwaltung wird in der Website nutzerfreundlich dargestellt. 

== Kontextabgrenzung
image:models/analysis/fitnessstudio_context.svg[fitnessstudio_context]

== Lösungsstrategie
=== Erfüllung der Qualitätsziele
[options="header"]
|=== 
|Qualitätsziel |Lösungsansatz
|... |...
|===

=== Softwarearchitektur
image::models/analysis/fitnessstudio_top_level.svg[fitnessstudio_top_level]



Client Server Model


^<br>
|<br>
|<br>
|

=== Entwurfsentscheidungen
* Verwendete Muster
* Persistenz
* Benutzeroberfläche
* Verwendung externer Frameworks

[options="header", cols="1,3,3"]
|===
|Externe Klasse |Pfad der externen Klasse |Verwendet von (Klasse der eigenen Anwendung)
|... |... |...
|===

== Bausteinsicht
* Entwurfsklassendiagramme der einzelnen Packages

[options="header"]
|=== 
|Klasse/Enumeration |Description
|===

=== Rückverfolgbarkeit zwischen Analyse- und Entwurfsmodell

[options="header"]
|===
|Klasse/Enumeration (Analysemodell) |Klasse/Enumeration (Entwurfsmodell)
|===

== Laufzeitsicht
* Komponentenbezogene Sequenzdiagramme, welche darstellen, wie die Anwendung mit externen Frameworks (zB. Salespoint, Spring) interagiert.

== Technische Schulden
* Auflistung der nicht erreichten Quality Gates und der zugehörigen SonarQube Issues

