= Test-Plan

Dieser Testplan stellt eine vereinfachte Version der IEEE 829-1998 Vorlage dar. +
Er befasst sich mit der Fitnessstudio Website, die von der Gruppe 16 im Rahmen des Softwaretechnologieprojektes 2019/20 an der Universität Dresden erstellt wird.

== Einführung
Um ein organisiertes und systematisches Testen zu ermöglichen, werden in diesem Dokument zum System passende Testfälle entworfen. Außerdem werden die Anforderungen an Hard- und Software definiert. +
Der Testplan richtet sich an den Kunden, an das Entwicklerteam und dabei insbesondere an die Implementierer der Testklassen.

== Aufbau der Testbezeichner
Nach welchem Schema sind die Tests benannt?

*Bsp.*

*U - Unit Test, I - Integrationstest, S - Systemtest*

*U-1, U-2, I-1*

== Test Gegenstände

== Zu testende Funktionalitäten

== Nicht zu testende Funktionalitäten
Die Bibliotheken java.time und org.javamoney.moneta, sowie das Framework Spring und SalesPoint müssen nicht erneut getesten werden. Hier stehen nur die Schnittstellen zu systemeigenen Klassen im Fokus. +
Einfache Methoden von Java-Klassen, wie z.B. setter und getter, die lediglich auf ein Attribut eines Objektes zugreifen, brauchen nicht getestet zu werden.

== Herangehensweise
*Bsp.:*

*Klassen werden mit JUnit getestet.*

*Integrationstest nach Bottom-Up Prinzip*

== Umgebungsvoraussetzungen
* Wird spezielle Hardware benötigt?
* Welche Daten müssen bereitgestellt werden? Wie werden die Daten bereitgestellt?
* Wird zusätzliche Software für das Testen benötigt?
* Wie kommuniziert die Software während des Testens? Internet? Netzwerk?

== Testfälle und Verantwortlichkeit
Jede testbezogene Aufgabe muss einem Ansprechpartner zugeordnet werden.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="headers"]
|===
|ID |Anwendungsfall |Vorbedingungen |Eingabe |Ausgabe

|U-1
|Discount d.isAvailable()
|LocalDate.now() ist zwischen d.startDate und d.endDate
|-
|true

|U-2
|Discount d.isAvailable()
|LocalDate.now() ist nicht zwischen d.startDate und d.endDate
|-
|false

|===
